version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.opencsv:opencsv
    versions:
    - ">= 5.a"
    - "< 6"
