package org.stormroboticsnj.ui.rank;

public enum RankEnum {
    POWER_CELLS_BOTTOM_AUTO,
    POWER_CELLS_OUTER_AUTO,
    POWER_CELLS_INNER_AUTO,
    POWER_CELL_PICKUP,
    POWER_CELLS_BOTTOM_TELEOP,
    POWER_CELLS_OUTER_TELEOP,
    POWER_CELLS_INNER_TELEOP,
    POWER_CELLS_BOTTOM_ENDGAME,
    POWER_CELLS_OUTER_ENDGAME,
    POWER_CELLS_INNER_ENDGAME,
    POWER_CELLS_ENDGAME,
    POWER_CELLS_AUTO,
    POWER_CELLS_TELEOP,
    CYCLE_TIME,
    ROTATION_CONTROL,
    POSITION_CONTROL,
    ENDGAME_LEVEL_HANG,
    ENDGAME_HANG;
}
